### ISSUE TITLE
udm-boot won't start after re-boot on UDM PRO SE 

### ISSUE THREAD

**Issue by mayankst** [boostchicken/udm-utilities#282] opened 2021-12-03 00:17 UTC
**Describe the bug**

After reboot udm-boot service won't start and gives `UDM-SE bash[1068]: Cannot find device "br3.mac"` error. If I use `systemclt restart udm-boot` then it starts fine.

Here are the contents of the service file.

```
[Unit]
Description=Run On Startup UDM
Wants=network-online.target
After=network-online.target

[Service]
Type=forking
ExecStart=bash -c 'mkdir -p /mnt/data/on_boot.d && find -L /mnt/data/on_boot.d -mindepth 1 -maxdepth 1 -type f -print0 | sort -z | xargs -0 -r -n 1 -- bash -c \'if test -x "$0"; then echo$

[Install]
WantedBy=multi-user.target
```

**To Reproduce**
1. Reboot UDM
2. Check service status by `systemctl status udm-boot`
3. See error

Dec 02 16:08:09 UDM-SE bash[1068]: Cannot find device "br3.mac"
Dec 02 16:08:09 UDM-SE bash[1068]: grep: /run/dnsmasq.conf.d/custom.conf: No such file or directory
Dec 02 16:08:09 UDM-SE bash[1068]: /mnt/data/on_boot.d/10-dns.sh: line 66: /run/dnsmasq.conf.d/custom.conf: No such file or directory
Dec 02 16:08:09 UDM-SE bash[1068]: cat: /run/dnsmasq.pid: No such file or directory
Dec 02 16:08:09 UDM-SE bash[1068]: /mnt/data/on_boot.d/10-dns.sh: line 67: kill: `': not a pid or valid job spec
Dec 02 16:08:10 UDM-SE bash[1068]: time="2021-12-02T16:08:10-08:00" level=error msg="Error tearing down partially created network namespace for container 27261102b83a6e1e62185deb0148fe277c
Dec 02 16:08:10 UDM-SE bash[1068]: Error: unable to start container "27261102b83a6e1e62185deb0148fe277c7d6976872d7d99844f20f632b93b38": error configuring network namespace for container 27
Dec 02 16:08:10 UDM-SE systemd[1]: udm-boot.service: Succeeded.
Dec 02 16:08:10 UDM-SE systemd[1]: Started Run On Startup UDM.
Dec 02 16:08:10 UDM-SE systemd[1]: udm-boot.service: Consumed 2.086s CPU time.

**Expected behavior**
Service should start successfully

On call restart service starts fine with following output

root@UDM-SE:~# systemctl restart udm-boot
root@UDM-SE:~# systemctl status udm-boot
● udm-boot.service - Run On Startup UDM
   Loaded: loaded (/etc/systemd/system/udm-boot.service; enabled; vendor preset: enabled)
   Active: active (running) since Thu 2021-12-02 16:11:22 PST; 1s ago
  Process: 11559 ExecStart=/bin/bash -c mkdir -p /mnt/data/on_boot.d && find -L /mnt/data/on_boot.d -mindepth 1 -maxdepth 1 -type f -print0 | sort -z | xargs -0 -r -n 1 -- bash -c 'if test
 Main PID: 11880 (conmon)
    Tasks: 2 (limit: 4726)
   Memory: 77.5M
      CPU: 2.054s
   CGroup: /system.slice/udm-boot.service
           ├─11880 /usr/libexec/podman/conmon --api-version 1 -c 27261102b83a6e1e62185deb0148fe277c7d6976872d7d99844f20f632b93b38 -u 27261102b83a6e1e62185deb0148fe277c7d6976872d7d99844f20f
           ├─11891 s6-svscan -t0 /var/run/s6/services
           ├─11969 s6-supervise s6-fdholderd
           ├─12322 pihole-FTL test
           ├─12396 s6-supervise lighttpd
           ├─12397 s6-supervise cron
           ├─12398 s6-supervise pihole-FTL
           ├─12401 bash ./run
           ├─12402 bash ./run
           ├─12404 bash ./run
           ├─12415 lighttpd -D -f /etc/lighttpd/lighttpd.conf
           ├─12418 /usr/sbin/cron -f
           ├─12429 /usr/bin/php-cgi
           └─12431 pihole-FTL no-daemon

Dec 02 16:11:18 UDM-SE systemd[1]: Starting Run On Startup UDM...
Dec 02 16:11:18 UDM-SE bash[11559]: udm-boot.service: running /mnt/data/on_boot.d/05-install-cni-plugins.sh
Dec 02 16:11:19 UDM-SE bash[11559]: Pouring /mnt/data/.cache/cni-plugins/cni-plugins-linux-arm64-v1.0.1.tgz
Dec 02 16:11:21 UDM-SE bash[11559]: udm-boot.service: sourcing /mnt/data/on_boot.d/10-dns.sh
Dec 02 16:11:21 UDM-SE bash[11559]: grep: /run/dnsmasq.conf.d/custom.conf: No such file or directory
Dec 02 16:11:22 UDM-SE bash[11559]: pihole
Dec 02 16:11:22 UDM-SE systemd[1]: Started Run On Startup UDM.

**Comment by boostchicken** [comment] 2021-12-03 04:41
It's running, it seems like an error is stopping it.  Also is this on an SE?  that 10-dns.sh file def isn't configured for the SE or tested on it.

**Comment by boostchicken** [comment] 2021-12-03 04:42
i dont think you need udm-boot on the SE, you have systemd at your disposal yes?

**Comment by mayankst** [comment] 2021-12-03 07:33
Yes have systemd, so just start the podman container instead?

**Comment by mazzy89** [comment] 2021-12-03 08:19
I can confirm that `10-dns.sh` works on the SE. I'm using it because unfortunately the systemd version there is really old and I can't create perfectly the network devices with `.network` unit. so I still continue to use those scripts to put up and configure network devices.
but in general @mayankst use systemd. I'm using mostly for everything. the only thing scripted is the CNI installation and the DNS interface `br` inteface bootstrap.

**Comment by mayankst** [comment] 2021-12-03 20:30
@mazzy89 Can you please help me move to `systemd` only?

**Comment by mazzy89** [comment] 2021-12-03 20:39
it's better you would ask here exactly what you are trying to achieve. if you are running `10-dns.sh` I assume you are trying to run adguard home or similar to your UDM. in that case as I said the interfaces management (brVLAN.mac, promisc mode, etc...) in my case is still entirely managed by that script `10-dns.sh` and by extension to the `udm-boot.service` unit. the installation of the CNIs needed by Podman the same. the rest (tailscale, IPV6 sit tunnel, lifecycle of containers, etc...) is managed by systemd. Now migrate everything to systemd is a massive amount of work and it depends what you are trying to do.

**Comment by mayankst** [comment] 2021-12-03 20:47
My current setup is podman with cni and udm-boot for running pu-hole. This seems to work fine in general but when UDM re-boots, the udm-boot service has errors because it cannot detect br interface. After reboot if I start it manually then it works just fine. So, basically if someone can help fix this issue then thats all I am looking for.

**Comment by mazzy89** [comment] 2021-12-03 21:11
ok so my recommendation is to avoid using systemd to achieve what `10-dns.sh` is trying to achieve. as I said the shipped systemd is the 241 which is buggy and lacks a lot of features. of course you could say well then let's update it. the fact is UDM PRO SE is shipped w/ the Debian 9 version quite an old version. you could get systemd newer version to some other sources but the side effect of updating an OS that runs a lot of UniFI services w/ systemd to a newer version well is very disruptive. you could break easily the appliance.

That being said the error seems here

```
Dec 02 16:08:09 UDM-SE bash[1068]: Cannot find device "br3.mac"
```

the `10-dns.sh` for some reasons fail.  I haven't encountered this issue. so it's hard to guess. but let's try to debug from here. please set in your script on top after the shebang `set -x`. reboot your device and you will see what the script execute. we'll find out the exact command that return an exit code that makes systemd unhappy. beside that which UDM PRO SE OS version are you running? when I've installed everything I've run 2.2.12. now i'm running the last.

**Comment by mayankst** [comment] 2021-12-03 21:35
OS version is 2.3.7

I removed `br3` from `FORCED_INTFC` which got rid of the br3 error but issue remains. Attaching log file with `set -x`

[udm-boot.log.txt](https://github.com/boostchicken/udm-utilities/files/7652447/udm-boot.log.txt)

**Comment by mazzy89** [comment] 2021-12-03 21:39
but you do not have any issues w/ the unit. it's clearly written

```
udm-boot.service: Succeeded.
```

Not sure then which error are you referring to.

**Comment by mayankst** [comment] 2021-12-03 21:42
This one, so I guess ser

time="2021-12-03T13:23:03-08:00" level=error msg="Error tearing down partially created network namespace for container 27261102b83a6e1e62185deb0148fe277cDec 03 13:23:03 UDM-SE bash[1078]: Error: unable to start container "27261102b83a6e1e62185deb0148fe277c7d6976872d7d99844f20f632b93b38": error configuring network namespace for container

**Comment by mazzy89** [comment] 2021-12-03 21:47
ok then let's do in this way. remove from `10-dns.sh` all the part related to boot/start the podmain container and move that in a systemd service. podman in that is very hand and it will help you a lot

so once you have started your udm run pihole w/ podman. then once the container is UP and running run

```
podman generate systemd --new pihole > /etc/systemd/system/pihole.service
```
this will create a systemd unit service.

now stop pihole container and run

```
systemctl daemon-reload
systemctl enable pihole
systemctl start pihole
```

Important thing. since your approach is to create interfaces via `10-dns.sh` which is executed by `udm-boot.service` make sure that `pihole.service` depends by `udm-boot`. How?

in the generated `pihole.service` add `udm-boot.service` to the `Requires` and `After` directives.

**Comment by mayankst** [comment] 2021-12-03 22:29
Moved the pi-hole to separate service as you suggested and issue still remains. 

I tried adding `ExecStartPre=/bin/sleep 30` to `udm-boot.service` and that did help. If I remove it then issue comes back again. So, definitely some timing issue.

**Comment by mazzy89** [comment] 2021-12-03 22:36
If you run the pihole service after the network is up and udm-boot service is active then I can't see how podman would fail since everything would be already in place. I think you have somewhere some systemd misconfig for sure.
All my systemd services get activated correctly. Anyway if the sleep helped you fine with that.

**Comment by mazzy89** [comment] 2021-12-03 22:43
Also note that I've told you to delete from the 10-dns script the podman start/run. So if you delete than the error would be transfered to the systemd pihole service. In that case you just set the pihole service to activate after udm-boot service and the error will be gone for sure. As said some issues for sure with your way to configure. Anyway if this solved your issue closing I'll close this issue.

**Comment by mayankst** [comment] 2021-12-03 22:47
I mean config by service looks ok, so not sure what's the problem. Hopefully sleep doesn't have any side affects. 

```
[Unit]
Description=Run On Startup UDM
Wants=network-online.target
After=network-online.target

[Service]
Type=forking
ExecStartPre=/bin/sleep 10
ExecStart=bash -c 'mkdir -p /mnt/data/on_boot.d && find -L /mnt/data/on_boot.d -mindepth 1 -maxdepth 1 -type f -print0 | sort -z | xargs -0 -r -n 1 -- bash -c \'if test -x "$0"; then echo$

[Install]
WantedBy=multi-user.target

```


```
# container-27261102b83a6e1e62185deb0148fe277c7d6976872d7d99844f20f632b93b38.service
# autogenerated by Podman 3.4.2
# Fri Dec  3 13:51:10 PST 2021

[Unit]
Description=Podman container-27261102b83a6e1e62185deb0148fe277c7d6976872d7d99844f20f632b93b38.service
Documentation=man:podman-generate-systemd(1)
Wants=network-online.target udm-boot.servive
After=network-online.target udm-boot.service
Requires=udm-boot.service
RequiresMountsFor=%t/containers

[Service]
Environment=PODMAN_SYSTEMD_UNIT=%n
Restart=always
TimeoutStopSec=70
ExecStartPre=/bin/rm -f %t/%n.ctr-id
ExecStart=/usr/bin/podman run --cidfile=%t/%n.ctr-id --cgroups=no-conmon --rm --sdnotify=conmon --replace -d --network dns --name pihole -e "TZ=America/Los Angeles"  -v /mnt/data/etc-pihole/:/etc/pihole/ -v /mnt/data/pihole/etc-dnsmasq.d/:/etc/dnsmasq.d/ --dns=127.0.0.1 --dns=1.1.1.1 --dns=8.8.8.8 --hostname pi.hole -e VIRTUAL_HOST=pi.hole -e PROXY_LOCATION=pi.hole -e ServerIP=192.168.4.3 -e IPv6=False pihole/pihole:latest
$ExecStop=/usr/bin/podman stop --ignore --cidfile=%t/%n.ctr-id
ExecStopPost=/usr/bin/podman rm -f --ignore --cidfile=%t/%n.ctr-id
Type=notify
NotifyAccess=all

[Install]
WantedBy=multi-user.target default.target
```

**Comment by mazzy89** [comment] 2021-12-03 22:49
Why to use wants and requires directives at the same time?

**Comment by mayankst** [comment] 2021-12-03 22:50
Because I am noob and don't know what I am doing (mostly). will remove requires.

**Comment by mayankst** [comment] 2021-12-03 22:53
@mazzy89 Thanks for all your help with this and fast replies. Even with workaround I am happy that it is working and hopefully 🤞will continue to work reliably. I hope this thread will help others since more people are buying SE devices now.

**Comment by mazzy89** [comment] 2021-12-03 22:54
No worries we have been all noobs ans we are all still noobs in every areas. There is too many to know out there. 

You want to read this here https://unix.stackexchange.com/questions/388586/systemd-requires-vs-wants

But I suggest to not remove requires but remove wants.

**Comment by mazzy89** [comment] 2021-12-03 22:56
You're welcome. No worries. The biggest problem,however is that SE are early access machines and tbh I really do not know what is going to happen. Will ubiquiti move to this approach and leave behind the udm pro way? Who know. Let's see if the SE will be the standard se facto.

**Closed** 2021-12-07 15:40 UTC
