### ISSUE TITLE
Web Interface Unreachable after a few days

### ISSUE THREAD

**Issue by reuter** [boostchicken/udm-utilities#40] opened 2020-08-31 14:07 UTC
Running a UDM Base on 1.8.0 with NextDNS and boot scripts set up.
Since I installed the boot scrips and NextDNS when on 1.7.2 everything works great for a few days. Then, after 2-3 days the Web Interface for the UDM becomes unavailable (Timed out / Site can't be reached). I upgraded to 1.8.0 hoping that might fix things, but it did not.

I can SSH into the UDM and issue a reboot, which fixes the problem again for a few days.

Not sure what info you would like that I can provide to hep troubleshoot. But, happy to help and happy to be a guinea pig if needed.

**Comment by Allram** [comment] 2020-08-31 15:04
I think this is a problem with UDM itself and not this repo. I have the same problem on both of my UDMP, one is with this mod and another is pure 1.8.0, both get unresponsive after a few days/hours.

**Comment by reuter** [comment] 2020-08-31 15:05
Hmmm, that's a good point. I changed too much at once. I upgraded to 1.7.2 and then installed the boto scripts/NextDNS at the same time.

**Comment by jason-stiefel-ck** [comment] 2020-08-31 20:45
I had this same problem on 1.7.2 when running Adguard and wpa-supplicant. I made the (painful) migration to 1.8.0 by backing up my network and protect apps, then doing a factory reset and starting fresh. It's been stable for 3 days now (I'm only running wpa-supplicant so far, not sure if I'll go back to running adguard anytime soon) 

I did find a problem I think I created at some point while experimenting. Check your `/mnt/data/unifi-os/unifi/logs/server.log` file and make sure you're not getting log bombed about having a duplicate `eth8` interface. If you are - there is a nice script at https://github.com/pbrah/eap_proxy-udmpro/blob/master/docker/fixit.py you can run to clear that up and _MAYBE_ that will fix the instability. I wish I had tried that first before I went through the upgrade but the timing didn't work out.

**Comment by SturdyErde** [comment] 2020-09-01 14:20
Yes, this is a known issue with UDM, and not a problem with this repo. I would suggest closing this issue.

**Closed** 2020-09-01 14:21 UTC

**Comment by ghvader** [comment] 2020-09-09 23:09
@reuter @SturdyErde @Allram @jason-stiefel-ck are any of you by chance running the lets encrypt mod list on the front page of this mod? I too was have a problem with the web interface, i disabled the cron job of the lets encrypt script because it appears every day at 3am it shutsdown the unif-os and then re-starts it. and it didnt' seem to always get restarted. so i would ssh in and unif-os restart and all was good.. few days later, same thing. so i just disabled that cron job and no problems so far.  so i just wanted to throw that out there incase any of you had the same issue.

**Comment by SturdyErde** [comment] 2020-09-10 00:47
I have definitely had that problem for several weeks, but only just began using the LE container last week. For me, it doesn't seem to be the cause, but I'll definitely keep my eyes on it!

**Comment by SturdyErde** [comment] 2020-09-10 00:48
I had actually been thinking about my own script to restart unifi-os because of its apparent instability.

**Comment by reuter** [comment] 2020-09-10 00:56
Just to follow up on this one from my end.
Fingers crossed, but I updated the firmware on all my devices (NanoHD, 2 x 8 port POE switches and 2 BeaconHD). Still running 1.7.2 and the controller is still at 5.14.22. It's been a few days now and (knock on wood) haven't had to reboot the UDM and the pages are still accessible.

@ghvader Not running Let's Encrypt on my side, no.

**Comment by SturdyErde** [comment] 2020-09-10 00:58
Nice. I'm a little further ahead on the UDM firmware and the controller version. There has been no significant improvement for my small network at home, but thankfully there has not been any of the problems that others suffer from on these betas and RCs.
